### ISSUE TITLE
routes using (bidi.bidi/alts ) don't match schema bidi.schema/RoutePair

### ISSUE THREAD

**Issue by mruzicka** [juxt/bidi#106]
Here is an example:
```clojure
(schema.core/validate
  bidi.schema/RoutePair
  [(bidi.bidi/alts ["/index.html" "/index"]) :index])
ExceptionInfo Value does not match schema: [(named (not (some (check % a-bidi.bidi.Alternates) schemas)) "") nil]  schema.core/validate (core.clj:176)
```

Should ```bidi.schema/Pattern``` include something like:
```clojure
(s/pred (partial satisfies? bidi.bidi/Pattern))
```
?

**Comment by SevereOverfl0w** [comment]
This is an issue. I've written a test case for it.

However satisfaction of bidi.bidi/Pattern makes other schemas become valid when they shouldn't. Satisfying that protocol is very broad, and I think the schema implementation is determined to be very picky.

Options:
  - Match on every special type we want to allow (Alternates, Files, etc.)
  - Make schema more broad in general
  - Something else?
