### ISSUE TITLE
Current version does not work with (use 'bidi.bidi). README outdated.

### ISSUE THREAD

**Issue by elrob** [juxt/bidi#112]
I can't get bidi to load in the REPL any more.

If I have version 1.24.0 in my project.clj, `(use 'bidi.bidi)` fails with `java.io.FileNotFoundException`
Doing the same with version 1.20.3 is fine.

Or I'm missing something?

**Comment by SevereOverfl0w** [comment]
I can't reproduce this on a clean leiningen app. The namespace is still the same.

I might guess that this is a .cljc issue, is your lein updated? There's a bug in versions <2.5.2 that cause .cljc code not to work.

`lein upgrade` will bump up your version.

**Comment by elrob** [comment]
Fixed. Thank you.

Turns out I needed to upgrade the clojure version in my project from 1.6.0 to 1.7.0.

Discovered by generating a clean leiningen app after `lein upgrade` and comparing the project.clj files with my current one.

**Comment by elrob** [comment]
Is there something that can be changed to make this more obvious to anyone else who has this issue?
As it seems bidi now has a dependency on a minimum lein/clojure version?

**Comment by malcolmsparks** [comment]
I've just pushed a note in the README which I hope makes this more explicit. There have been a few difficulties with the transition to .cljc but the advantages of migrating I feel outweigh the disadvantages. Previous versions of bidi that used .cljx were difficult to work with, certainly in the REPL.

Users of Clojure 1.6 can still use earlier versions of bidi.
