### ISSUE TITLE
Simplest example fails

### ISSUE THREAD

**Issue by timur87** [juxt/bidi#122]
(def my-routes ["/" {"i" :index}])

(match-route my-routes "/i")

Returns nil, am I doing something wrong?

**Comment by malcolmsparks** [comment]
For me it returns `{:handler :index}` as expected.

```clojure
(ns bidi.play
  (:require [bidi.bidi :as bidi]))

(def my-routes ["/" {"i" :index}])

(bidi/match-route my-routes "/i")
```

Can you give a bit more information?

**Comment by timur87** [comment]
I believe this issue is caused by yada. I will post it over there and I'm closing this here.

**Comment by malcolmsparks** [comment]
Ah, quite possibly! yada has recently added meaning to a bidi map (it interprets it has a resource model). Obviously `{"i" :index}` isn't a proper resource-model.

I have changed my mind about this, I think it's no longer a good idea and will be removing it.
