### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by niwinz** [juxt/bidi#126]
Hi!

I’m interested in what have changed between 1.25.0 and 2.0.0?

Also, any chance we can have a changelog published somewhere?

**Comment by malcolmsparks** [comment]
The only significant change is the introduction of a virtual-hosts model
which allows an entire tree of hosts (and possibly routes from other
services) to be treated as a single data structure. This change broadens
bidi's scope sufficiently to warrant a major version increment.


Malcolm Sparks
Director

Email: malcolm@juxt.pro
Web: https://juxt.pro

JUXT LTD.
Software Consulting, Delivery, Training

**Comment by niwinz** [comment]
Nice, thanks. 

Would be awesome have a CHANGES.md or similar file in the repository with public changelog. This will help to bidi users about possible api/bahevior changes when they upgrade to new version of bidi.

**Comment by atroche** [comment]
Ah, I spent a little while trying to work this out too. Often a major release indicates breaking changes. Thanks for clarifying!

**Comment by malcolmsparks** [comment]
My own opinion on Changelog files is that they should be (strictly)
unnecessary if commits are well commented and the right granularity. Of
course, this is not always the case, but I'd prefer to strive towards that
goal than have to maintain a separate Changelog.

However, I see that people are confused about the jump from 1.x to 2.x so
I've pushed a note to the README.md in
773d932c92be3e7cecf6504bcb95f7c58dde90b8

**Comment by niwinz** [comment]
Sorry but commits are not good changelog. Changelog is not about granular changes, is about relevant changes that user should know, like breaking changes, new features and similar things. Commits are good but them are too much detailed and low level for the Changelog purpose.

my two cents.
