### ISSUE TITLE
Pedestal's new routing is standalone

### ISSUE THREAD

**Issue by ohpauleez** [juxt/bidi#136]
Hi all!

Regarding the table in the README, I think Pedestal should have checkmarks in all the columns.  Both the route definition and the router specification are programmed against protocols (fully extensible), and recently was just separated as a standalone project/module.

**Comment by malcolmsparks** [comment]
Hi Paul - I've made the corrections!


Malcolm Sparks
Director

Email: malcolm@juxt.pro
Web: https://juxt.pro

JUXT LTD.
Software Consulting, Delivery, Training

**Comment by ohpauleez** [comment]
Excellent!  Thanks!
