### ISSUE TITLE
Breaking change to match-route with hosts in 2.x

### ISSUE THREAD

**Issue by jarohen** [juxt/bidi#139]
Hey Malcolm/all :)

Got a slight break when upgrading from 1.25.0 to 2.0.8 - I'm not sure if the below was ever intended functionality, and the workaround's pretty straightforward, but thought I'd flag in case someone else hits it:

1.25.1:
```
user=> (require '[bidi.bidi :as bidi])
nil
user=> (bidi/match-route ["" {"/foo" :foo-handler}] "http://localhost:3000/foo")
{:handler :foo-handler}
```

2.0.8:
```
user=> (require '[bidi.bidi :as bidi])
nil
user=> (bidi/match-route ["" {"/foo" :foo-handler}] "http://localhost:3001/foo")
nil
```

HTH!

James

**Comment by jarohen** [comment]
(cc @bronsa)

**Comment by malcolmsparks** [comment]
That's interesting. I wouldn't have expected the former to have ever worked, because bidi matches paths only - the matching of different hosts is now supported, via the vhosts functionality that was introduced in 2.0.0.

Do you think this needs a fix or can I close the issue?

**Comment by SevereOverfl0w** [comment]
This may have happened because of the PR where I used goog.uri / Java.net.url, in order to pull just the path from input.

This was in order to handle the query params input, primarily for cljs.

On 24 August 2016 17:08:47 BST, Malcolm Sparks <notifications@github.com> wrote:
>That's interesting. I wouldn't have expected the former to have ever
>worked, because bidi matches paths only - the matching of different
>hosts is now supported, via the vhosts functionality that was
>introduced in 2.0.0.
>
>Do you think this needs a fix or can I close the issue?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/juxt/bidi/issues/139#issuecomment-242121180

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jarohen** [comment]
@malcolmsparks: yeah, don't think it needs a fix with the new vhosts functionality - I doubt it was ever meant to support that use case anyway!

Will leave it here as documentation just in case anyone else hits it :)
