### ISSUE TITLE
support redirects in the cljs router

### ISSUE THREAD

**Issue by thedavidmeister** [juxt/bidi#144]
it would be nice to be able to setup redirects with https://github.com/juxt/bidi/blob/master/src/bidi/router.cljs somehow

**Comment by kwladyka** [comment]
cljs use case example
If you open `:log-in` handler and you are logged, then redirect to `:main`.
If you open `:panel-x` and you are not logged, then redirect to `:log-in` and after that redirect back go `:panel-x` and this should work with parameters also.

clj example
This will be more about authentication and authorisation, also redirect after POST request.

Then it will be useful. But it seems to be not part of bidi itself.
I think the issue should be closed. Unless you see it differently?

**Comment by thedavidmeister** [comment]
i don't remember what i was trying to do, i opened this over 2 years ago ;)
