### ISSUE TITLE
Limitations when using same handler for different routes

### ISSUE THREAD

**Issue by ragnard** [juxt/bidi#5]
Hi,

First of all, thanks for a fantastic library, really enjoying using bidi with Liberator. The bi-directionality and routes as data is great!

I encountered a few issues when defining a route structure that has the same handler occurring multiple times. I'm not sure whether this is because it's a bad idea to do that, but let me show you the example I'm using:

 ```clojure
(def routes
  ["/" [["posts" 'posts-handler]
        [["users/" :user "/posts"] 'posts-handler]]])
```

In this case, `posts-handler` understands queries both for all posts (first route), and for a specific users posts (second route). 

Given this route structure, I would like to be able to generate URLs both for all posts, and a specific users posts like so:

```clojure
(path-for routes 'posts-handler)
;; => "/posts"
(path-for routes 'posts-handler :user "blahonga")
;; => "/users/blahonga/posts"
```

ie. if params are given, routes where the params occur should be preferred. It may even make sense to fail completely if all params supplied are not used. I'm not sure.

Currently the unmatching takes the first route matching the given handler. However, the first case in the above `path-for` example actually blows up with `clojure.lang.ExceptionInfo: Cannot form URI without a value given for :user parameter` (full stack trace below). I believe this is due to non-lazyness (or lazy-seq chunking),  `unresolve-handler` for PersistentVectors uses:

```clojure
(first (keep #(match-pair % m) this))
```

Which seems to be not lazy for `PersistentVectors`.

Full stack trace:

```
clojure.lang.ExceptionInfo: Cannot form URI without a value given for :user parameter
 at clojure.core$ex_info.invoke (core.clj:4327)
    bidi.bidi$eval28675$fn__28678.invoke (bidi.clj:56)
    bidi.bidi$eval28612$fn__28624$G__28599__28631.invoke (bidi.clj:33)
    bidi.bidi$eval28811$fn__28812$fn__28813.invoke (bidi.clj:133)
    clojure.core$map$fn__4207.invoke (core.clj:2485)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:60)
    clojure.lang.RT.seq (RT.java:484)
    clojure.core$seq.invoke (core.clj:133)
    clojure.core$apply.invoke (core.clj:617)
    bidi.bidi$eval28811$fn__28812.invoke (bidi.clj:133)
    bidi.bidi$eval28711$fn__28725$G__28700__28732.invoke (bidi.clj:80)
    bidi.bidi$unmatch_pair.invoke (bidi.clj:152)
    bidi.bidi$eval28898$fn__28899$fn__28900.invoke (bidi.clj:160)
    clojure.core$keep$fn__6349.invoke (core.clj:6599)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:60)
    clojure.lang.LazySeq.first (LazySeq.java:82)
    clojure.lang.RT.first (RT.java:577)
    clojure.core$first.invoke (core.clj:55)
    bidi.bidi$eval28898$fn__28899.invoke (bidi.clj:160)
    bidi.bidi$eval28754$fn__28768$G__28743__28775.invoke (bidi.clj:87)
    bidi.bidi$unmatch_pair.invoke (bidi.clj:151)
    bidi.bidi$path_for.doInvoke (bidi.clj:207)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    bidi.bidi$eval32697.invoke (form-init1346470612871071144.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6619)
    clojure.lang.Compiler.eval (Compiler.java:6582)
    clojure.core$eval.invoke (core.clj:2852)
    clojure.main$repl$read_eval_print__6588$fn__6591.invoke (main.clj:259)
    clojure.main$repl$read_eval_print__6588.invoke (main.clj:259)
    clojure.main$repl$fn__6597.invoke (main.clj:277)
    clojure.main$repl.doInvoke (main.clj:277)
    clojure.lang.RestFn.invoke (RestFn.java:1096)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__675.invoke (interruptible_eval.clj:56)
    clojure.lang.AFn.applyToHelper (AFn.java:159)
    clojure.lang.AFn.applyTo (AFn.java:151)
    clojure.core$apply.invoke (core.clj:617)
    clojure.core$with_bindings_STAR_.doInvoke (core.clj:1788)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke (interruptible_eval.clj:41)
    clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__716$fn__719.invoke (interruptible_eval.clj:171)
    clojure.core$comp$fn__4154.invoke (core.clj:2330)
    clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__709.invoke (interruptible_eval.clj:138)
    clojure.lang.AFn.run (AFn.java:24)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:615)
    java.lang.Thread.run (Thread.java:744)
```

**Comment by wilkerlucio** [comment]
Hi,

I just got into the same situation, these are my routes in question:

```clojure
(def routes ["/" {""   :index
                  "v/" {[:source-id] {""              :composition
                                      ["/" :track-id] :composition}}

                  "s/" {[:search] :search-results}}])
```

The `track-id` is an optional parameter, Bidi is able to match-route fine for both cases, but leaving the code as is the `path-for` only works without the `:track-id` (it's always ignored). By inverting the order I can generate with `:track-id` but trying otherwise will blow up (like discussed before).

Would be great to have this feature.

**Comment by isaksky** [comment]
This code looks like it is intended to solve this problem:
https://github.com/juxt/bidi/blame/335cb3165f873e8590199fcc20acb288104fe7ce/src/bidi/bidi.cljc#L451-L453

```
451	;; If you have multiple routes which match the same handler, but need to
452	;; label them so that you can form the correct URI, wrap the handler in
453	;; a TaggedMatch.
```

Just adding a wrapper, e.g., (tag :mytag 'handler) in both the routes and path-for just makes it return nil, however. Can you clarify @malcolmsparks ? Is that code related to this problem? If not, are you open for a pull request?

**Comment by malcolmsparks** [comment]
Actually is should be `(tag handler :mytag)` - the argument order of the TaggedMatch record was confusing (the `tag` function was switching the args around). I've cleaned that up in the last commit.

I think this issue, in general, is addressed by the use of tags. If you want the same handler at more than one route, you can use tags to distinguish between them. I'm concerned that an approach which involved path-for continuing it's journey until it had uncovered every possible match would impact performance for everyone.

**Comment by isaksky** [comment]
Sounds good, thank you!
