### ISSUE TITLE
Coupling question

### ISSUE THREAD

**Issue by christianromney** [juxt/bidi#52]
Hi there, 

I'm just discovering your awesome library, and I have an architectural question about your usage in the real-world. Allow me to setup the problem with some theoretical code

```clojure
(ns my.routes
  (:require [my.controllers.authentication :as auth]
                [cemerick.friend :as friend])

(def my-routes ["/logout" (wrap-middleware auth/logout friend/logout)
```

You can assume that I'm using bidi.ring/make-handler with my routes. Of course, route recognition and generation work marvelously. My question is one of coupling and indirection related to route generation (path-for). As I see it, there are two places where I might want to use path-for:

1. inside "controller" / Ring handler functions (especially for redirections)
2. in view-related code (I'm using Enlive) to update a hyperlink's HREF to point to the correct location.

It's the latter which concerns me. While it's natural for handlers to know about views (they have to render some representation), the converse is generally considered undesirable. But, if I have symbolic references to functions in the "dispatch" / handler position in my route definitions, then I need something along the lines of:

```clojure
(path-for auth-routes auth/logout) 
```
in my view layer (Enlive snippets).  Of course, we could solve the problem by introducing a layer of indirection such that instead of the bi-directional coupling being one of:

    URL path <===> dispatch function

it could be:

    URL path <===> *named route* / keyword <===> dispatch function

This would let us depend on an abstract *name* for route generation:

```clojure
(path-for auth-routes :logout)
```
at the expense of complicating our route recognition where we would have to do two lookups to go from URL path to dispatch function. As this would mean opting out of your carefully written *make-handler* function, I naturally wanted to get your thoughts / advice and ask how you approach this problem in your production code.

Thanks both for the library and for reading this far. 
Cheers!

**Comment by christianromney** [comment]
Doh—nevermind. I guess that's the whole point of the second arity in make-handler. I think I've got it, but would still love to know if I'm on the right track...

**Comment by christianromney** [comment]
ok passing a map from keyword to dispatch function as the second arg to make-handler addresses all my concerns. sorry for working through my mental process in your Github issues...

**Comment by malcolmsparks** [comment]
As of 1.18.0, the preferred way of referencing your handlers is by identifying them. See https://github.com/juxt/bidi#identifiablehandler

Until 1.18.0 this was left as a sort-of exercise for the reader, but it's such a common case I've decided to provide better guidance.

You can use the second arity of the make-handler, this second arity will remain to provide flexibility for those who need it.
