### ISSUE TITLE
Which is deprecated `handler` or `TaggedMatch`?

### ISSUE THREAD

**Issue by bensu** [juxt/bidi#54]
According to the [Docs](https://github.com/juxt/bidi#identifiablehandler) TaggedMatch is deprecated in favor of `handler` but in the [source](https://github.com/juxt/bidi/blob/master/src/bidi/bidi.cljx#L370) `handler` is also deprecated.

Is the whole feature deprecated?

**Comment by malcolmsparks** [comment]
No, the feature is really useful for path-for arguments. One should be deprecated. Currently I'm in favour of deprecating handler in favour of tag, because it can be used in -> threading.

**Comment by bensu** [comment]
Great thanks. Here is a PR to align the README with this info: #56

**Comment by bensu** [comment]
I'll close the issue since PR was merged, thanks!
