### ISSUE TITLE
Routing breaks when map size overflows into PersistentHashMaps

### ISSUE THREAD

**Issue by lbradstreet** [juxt/bidi#55]
Occurs because matches are only implemented for PersistentArrayMap, see https://github.com/juxt/bidi/blob/master/src/bidi/bidi.cljx#L251 and https://github.com/juxt/bidi/blob/master/src/bidi/bidi.cljx#L282 and not implemented for PersistentHashMap.

I found this on the clourescript side, not sure if it occurs on the clojure side.

**Comment by malcolmsparks** [comment]
Thanks, that definitely looks to be a bug.

**Comment by dustingetz** [comment]
Is a fix in the works or will a PR be accepted if I fix it? this is blocking me

**Comment by Lalaland** [comment]
dustingetz Clojure supports protocol extensions outside the implementing package, so you can just manually add the required definitions to your code.

```
(extend-protocol bidi.bidi/Pattern
  cljs.core.PersistentHashMap
  (match-pattern [this env]
    (when (every? (fn [[k v]]
                    (cond
                     (or (fn? v) (set? v)) (v (get env k))
                     :otherwise (= v (get env k))))
                  (seq this))
      env))
  (unmatch-pattern [_ _] ""))

(extend-protocol bidi.bidi/Matched
  cljs.core.PersistentHashMap
  (resolve-handler [this m] (some #(bidi.bidi/match-pair % m) this))
  (unresolve-handler [this m] (some #(bidi.bidi/unmatch-pair % m) this)))
```

**Comment by lbradstreet** [comment]
I'm guessing for cljs the protocol used by bidi should be IAssociative (should handle both cases). For the manual fix your probably want to use PersistentHashMap.

**Comment by malcolmsparks** [comment]
Happy to accept PRs

**Comment by jeffh** [comment]
Is it possible to get a snapshot or new release of this :smiley:? After we have too many routes in clojurescript we get this bug on bidi 1.18.11.

The temporary fix from @Lalaland works for now.
