### ISSUE TITLE
Can't serve ->Resources from /target

### ISSUE THREAD

**Issue by kernius** [juxt/bidi#61]
I am using [boot](https://github.com/boot-clj/boot) instead of Leiningen, and it treats /resources directory as read-only by [creating final artifacts](https://github.com/boot-clj/boot/wiki/Tasks) in /target.

How could I serve index.html from /target/index.html with bidi?

This only serves index.html from /resources/public/:

```
(def routes
  ["" [["" (->Resources {:prefix "public/"})]]])
```

**Comment by malcolmsparks** [comment]
If you can't add target/ to the classpath, can you use ->Files instead?

**Comment by kernius** [comment]
Thanks, solved.
