### ISSUE TITLE
Catch all

### ISSUE THREAD

**Issue by martinskou** [juxt/bidi#64]
Any method for making a route to catch all requests?

**Comment by kardan** [comment]
I used #".*", e.g.
```clojure
(def app-routes
  "Map out routes."
  ["/" [["" :home]
        ["app" :app]
        [#".*" :not-found]]])
```

**Comment by 4xrsJCr9** [comment]
You could use the `true` pattern (https://github.com/juxt/bidi#route-definitions) as a catch all.

**Comment by kardan** [comment]
Ah, didn't think about that, much better. That said I have sometimes missed a full working example in the readme.
