### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by james-henderson** [juxt/bidi#66]
Hi Malcolm - is there a quick way (short of going through the Git history) of finding breaking changes between versions of bidi?

Cheers,

James

**Comment by malcolmsparks** [comment]
Is there a particular breakage you are looking for?

I try not to break anything between releases, and keep redundant functions
around for a few major releases before removing them. Major releases are
where X changes in 1.X.y

**Comment by james-henderson** [comment]
> Is there a particular breakage you are looking for?

Not really, just had a couple of old apps on 1.12.0, wanted to upgrade them to 1.19.0, and wanted to check through a list of breaking changes to see what the migration path would look like. No worries if it doesn't already exist - seems to apply cleanly anyway :)

James

**Comment by malcolmsparks** [comment]
Unless you're using the query-params functionality (which has been removed since 1.12) I think you're good to upgrade. Try it and see ;)

**Comment by james-henderson** [comment]
Tried it, was good, thanks :)
