### ISSUE TITLE
Shouldn't the doc mention tag instead of ->TaggedMatch

### ISSUE THREAD

**Issue by Frozenlock** [juxt/bidi#70]
The source shows a function [tag](https://github.com/juxt/bidi/blob/ca694b46c28b73adffdd1fe458b41cc53e4173ea/src/bidi/bidi.cljx#L504). 

It is easier to type (and much prettier) than `->TaggedMatch`.

Shouldn't its use be encouraged in the readme?
`->TaggedMatch` feels like an implementation detail.

Edit: the same is true for `->Atlernates`.

**Comment by malcolmsparks** [comment]
Yes, I agree.

**Comment by malcolmsparks** [comment]
fixed
