### ISSUE TITLE
Protocol error on CLJS when matching routes on a map above a certain size

### ISSUE THREAD

**Issue by jarohen** [juxt/bidi#73]
Hi Malcolm,

Really enjoying using Bidi on CLJS btw, it makes links/routing much easier :)

Ran into a problem when my routes structure goes beyond a certain size - while `cljs.core.PersistentArrayMap` satisfies the `bidi.bidi/Matched` protocol, `cljs.core.PersistentHashMap`s don't!

Have fixed for now by adding the following in my app, copying from the implementation for ArrayMap:

```clojure
(extend-protocol bidi/Matched
  cljs.core.PersistentHashMap
  (resolve-handler [this m] (some #(bidi/match-pair % m) this))
  (unresolve-handler [this m] (some #(bidi/unmatch-pair % m) this)))
```

Guess it's a case of duplicating the implemention in Bidi too, or do you know of a cleaner solution?

Cheers :)

James

**Comment by meowcakes** [comment]
This was fixed in this commit https://github.com/juxt/bidi/commit/68c85c0f475e50e32ff6e5d08af6995f7cb7cc64

**Comment by jarohen** [comment]
Thanks :)
