### ISSUE TITLE
Migrate from .cljx to .cljc

### ISSUE THREAD

**Issue by malcolmsparks** [juxt/bidi#76]
Now that Clojure 1.7.0 is released, we need to move from .cljx to .cljc files.

I have done the initial port on the cljc branch. However, I somehow can't get the tests to work which I believe will be an issue until the next Leiningen is released. 

Lazily I'm hoping that time alone solves this issue, but we could move to something like boot.

**Comment by bensu** [comment]
Hi Malcom, `lein test` fails to find `.cljc` files. Progress is being tracked in [#1827](https://github.com/technomancy/leiningen/issues/1827). Time alone might solve it :)

**Comment by Skinney** [comment]
The tracked issue has been merged, and lein 2.5.2 should support .cljc files now.

**Comment by malcolmsparks** [comment]
Thanks for pointing this out. I think it's now time to investigate again.



Malcolm Sparks
Director

Email: malcolm@juxt.pro
Web: https://juxt.pro

JUXT LTD.
Software Consulting, Delivery, Training

On 9 October 2015 at 11:50, Robin Heggelund Hansen <notifications@github.com

**Comment by nwjsmith** [comment]
Fixed in https://github.com/juxt/bidi/pull/92
