### ISSUE TITLE
WARNING: uuid already refers to: cljs.core/uuid being replaced by: bidi.bidi/uuid at line 8 bidi/bidi.cljs

### ISSUE THREAD

**Issue by ul** [juxt/bidi#79]
Compile warning when used with org.clojure/clojurescript "0.0-3308"

**Comment by malcolmsparks** [comment]
Thanks.

Simply changing the function name would still break compatibility with
those using the feature which coerces path parameters to uuids, so I think
we'll have to ignore this warning for now until "0.0-3308" has sufficient
adoption we can move to cljs's uuid.

**Comment by Frozenlock** [comment]
Wouldn't this solve the issue?

https://github.com/juxt/bidi/pull/74

**Comment by ul** [comment]
AFAIK it should.

**Comment by jeroenvandijk** [comment]
@malcolmsparks I ran into this issue just now. I am trying bidi in a project in combination with `lein-figwheel`(*) where every warning stops code from loading. I need to figure out if, and if possible how, I can use `bidi` together with lein-figwheel and the latest clojurescript. 

So +1 on changing this

(thanks for the library btw, seems like something I want to use :-))

(*)  `[lein-figwheel "0.3.8"]` and ` [org.clojure/clojurescript "1.7.122"]`

**Comment by jeroenvandijk** [comment]
@malcolmsparks Never mind, I missed that `1.21.0` was [released](https://github.com/juxt/bidi/commit/f66090c14c474dee218be1f96deba68ea361dc4f). No warnings anymore! :-)
