### ISSUE TITLE
Mime type not correctly guessed

### ISSUE THREAD

**Issue by ericbmerritt** [juxt/bidi#84]
In using `->ResourcesMaybe` it seems that the mime-type for css isn't correctly guessed. In digging into the source, it looks like bidi uses `wrap-file-info` from `ring.middleware.file-info`. According to the discussion here: https://groups.google.com/forum/#!topic/ring-clojure/EmjsHw4QyEk. Use of `wrap-file-info` with resources is problematic. In my case, bidi sets the mime-type to be 'text/plain' and I see the following error in the browser console 'Resource interpreted as Stylesheet but transferred with MIME type text/plain: '

**Comment by Frozenlock** [comment]
Getting the same error with bidi `2.0.0`.
