### ISSUE TITLE
Update to ring 1.4.0

### ISSUE THREAD

**Issue by ricardojmendez** [juxt/bidi#86]
This is half feature request, half knowledge base in case someone else runs into the same problem.

Simply adding bidi 1.21.0 or 1.20.3  to a project that uses ring 1.4.0 causes a Null Pointer Exception when you attempt to run ring or the repl. You don't need to be using bidi yet for the error to appear.

The exception will be logged along the lines of:

```
#error {
 :cause nil
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.NullPointerException, compiling:(ring/util/http_response.clj:1068:1)
   :at [clojure.lang.Compiler load Compiler.java 7239]}
  {:type java.lang.NullPointerException
   :message nil
   :at [clojure.core$with_meta__4146 invoke core.clj 218]}]
 :trace
 [[clojure.core$with_meta__4146 invoke core.clj 218]
  [potemkin.namespaces$import_def invoke namespaces.clj 67]
  [clojure.lang.Var invoke Var.java 394]
  [clojure.lang.AFn applyToHelper AFn.java 165]
  [clojure.lang.Var applyTo Var.java 700]
...
]
}
```

The only namespace referenced from your project will likely be your handler, on line 1. Adding the dependency as `[bidi "1.21.0" :exclusions [ring/ring-core]]` solved the compiler exception (although I've yet to integrate it).

**Comment by nwjsmith** [comment]
This was fixed in b3496044dd518e2fded28b5888cedda16d4690b6
